# Generated by Django 5.0.4 on 2024-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='include',
            field=models.BooleanField(default=False),
        ),
    ]
