# Generated by Django 5.0.4 on 2024-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.BooleanField(default=True),
        ),
    ]
