# Generated by Django 5.0.4 on 2024-04-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['name']},
        ),
    ]
